import React from 'react';
import styled from 'styled-components';

const WalletIconContainer = styled.div`
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAMAAADVRocKAAABI1BMVEVHcEwAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADRGyDUAAAAYHRS
    TlMADs029+44ETPM/hMdFAnlIdV3/egkyQrmA/X6X2Tq7wHP1Piqzi5S/HsZvsMEKPHS9pQy+1s8
    4cKjhGVGrSzRDTESneDBxgKIJo3QDFT5lxZZOiDpq4wqCy9T2bo+48QfekkPAAABcklEQVRo3u3Z
    1W6EUBAGYCqURXYXVrsudXeXrbu7d97/KZq2h6Q3SIA/2TTzXw/zBThnICBJHA6H057Ry/2nGY2C
    pcuzvXI0QyHiCbxXiZDAwgVBgcU+ggJKlbDAA2EBvRsMlO2q3oqhBMyEG3Bv9zdAW7ghgDXUjLgT
    AOoEpLQAjlGAPeAq6DNIKiCgZC/T5noBAvwZRCVZJK1pWk32l6R6su0KRLCRtZUtLEA0vQMG6K0O
    BugFDYyhgfknL2A1J4cSJr2ADklK2PP91jRN3eezoCWO7/EBBEonAwwwwAADbQkkRnLWbhYHJA6+
    q6diMCD1W67CgE9RP4oCBkR9FgXMirf9AgqIZ37Kz3HLdHOc6GMIutF045BHBQMMMMDAfwNqoqCh
    BktRHP/sBFjRfEqguBNwGU3/puM1vIkGSDnfpY0o+u/lXf4fvIbvX5xzW2hX+2H7L8Xcl3L9enk4
    RHsrlffeLmePsYAZjEscDocTJF/AHj0sIBB5LwAAAABJRU5ErkJggg==
    ');
    background-position: 50% 50%;
    background-repeat: no-repeat;
    background-size: cover;
    height: 21px;
    width: 20px;
`;

export const WalletIcon = () => <WalletIconContainer />;
